version: '3'
services:
  ll_validator_mongo:
    container_name: ll_validator_mongo
    image: mongo
    volumes:
      - ./mongo_data:/data/db
    ports:
      - '27101:27017'
  ll_validator_redis:
    container_name: ll_validator_redis
    image: redis
    ports:
      - '6300:6379'
  ll-bridge-validator:
    container_name: ll-bridge-validator
    restart: unless-stopped
    image: lightlink/bridge-validator-testnet:latest
    ports:
      - '2710:8080'
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://ll_validator_mongo:27017/ll_bridge_validator
      - REDIS_HOST=ll_validator_redis
      - REDIS_PORT=6379
    links:
      - ll_validator_mongo
      - ll_validator_redis
volumes:
  mongo_data:
  app_data:
